[package]
name = "user_mgmt"
version = "0.1.0"
authors = ["Hamish Peebles <hamish.peebles@dfinity.org>", "Matt Grogan <matthew.grogan@dfinity.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = { path = "../../../../src/ic-cdk", version = "0.2.0" }
ic-cdk-macros = { path = "../../../../src/ic-cdk-macros", version = "0.2.0" }
ic-types = "0.1.1"
bimap = "0.5.3"
serde = "1.0.111"
shared = { path = "../shared", version = "0.1.0" }
